language: node_js
node_js:
  - "node"
notifications:
  email: false
sudo: true
before_script:
  - sudo apt-get -qq update
  - sudo apt-get install graphicsmagick
  - sudo apt-get install phantomjs
cache:
  directories:
    - "node_modules"
